use_frameworks!

def shared_pods
#  pod 'SwiftCharReader', :path => '../'
  pod 'SwiftCSVParser', :path => '../'
end

target 'SwiftCharReader_Example' do
  platform :ios, '8.0'
  shared_pods
end

target 'CharReadMac' do
  platform :osx, '10.14'
  shared_pods
end
